version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - rm -rf node_modules package-lock.json
      - npm cache clean --force
      - npm ci || npm install
  build:
    commands:
      - npm run build
      - cp appspec.yml dist/
      - mkdir -p dist/scripts
      - cp scripts/install.sh dist/scripts/
      - chmod +x dist/scripts/install.sh

artifacts:
  files:
    - '**/*'
  base-directory: dist
